// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vscode = require("vscode");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Core__Option = require("@rescript/core/lib/js/src/Core__Option.bs.js");
var Common$AgdaModeVscode = require("../View/Common.bs.js");

var diagnosticsCollection = {
  contents: undefined
};

function init() {
  var collection = Vscode.languages.createDiagnosticCollection("agda");
  diagnosticsCollection.contents = Caml_option.some(collection);
  return collection;
}

function getOrCreate() {
  var collection = diagnosticsCollection.contents;
  if (collection !== undefined) {
    return Caml_option.valFromOption(collection);
  } else {
    return init();
  }
}

function clear() {
  Core__Option.forEach(diagnosticsCollection.contents, (function (collection) {
          collection.clear();
        }));
}

function clearForUri(uri) {
  Core__Option.forEach(diagnosticsCollection.contents, (function (collection) {
          collection.delete(uri);
        }));
}

function parseErrorRange(errorText) {
  var range = Common$AgdaModeVscode.AgdaRange.parse(errorText);
  if (range !== undefined) {
    return range;
  }
  var firstLine = Core__Option.getOr(errorText.split("\n")[0], "");
  var position = firstLine.indexOf(": ");
  var rangeOnly = position > 0 ? firstLine.slice(0, position) : firstLine;
  return Common$AgdaModeVscode.AgdaRange.parse(rangeOnly);
}

function createDiagnostic(message, range, severity) {
  return new Vscode.Diagnostic(range, message, severity);
}

function setDiagnostics(uri, diagnostics) {
  Core__Option.forEach(diagnosticsCollection.contents, (function (collection) {
          collection.set(uri, diagnostics);
        }));
}

function addError($$document, message, rawRange) {
  var uri = $$document.uri;
  var range;
  if (rawRange !== undefined) {
    var match = parseErrorRange(rawRange);
    var exit = 0;
    if (match !== undefined && typeof match === "object") {
      var interval = match._1[0];
      range = interval !== undefined ? Common$AgdaModeVscode.AgdaInterval.toVSCodeRange(interval) : new Vscode.Range(new Vscode.Position(0, 0), new Vscode.Position(0, 1));
    } else {
      exit = 1;
    }
    if (exit === 1) {
      range = new Vscode.Range(new Vscode.Position(0, 0), new Vscode.Position(0, 1));
    }
    
  } else {
    range = new Vscode.Range(new Vscode.Position(0, 0), new Vscode.Position(0, 1));
  }
  var diagnostic = createDiagnostic(message, range, 0);
  var collection = getOrCreate();
  var existing = Core__Option.getOr(collection.get(uri), []);
  var newDiagnostics = existing.concat([diagnostic]);
  setDiagnostics(uri, newDiagnostics);
}

function addWarning($$document, message, rawRange) {
  var uri = $$document.uri;
  var range;
  if (rawRange !== undefined) {
    var match = parseErrorRange(rawRange);
    var exit = 0;
    if (match !== undefined && typeof match === "object") {
      var interval = match._1[0];
      range = interval !== undefined ? Common$AgdaModeVscode.AgdaInterval.toVSCodeRange(interval) : new Vscode.Range(new Vscode.Position(0, 0), new Vscode.Position(0, 1));
    } else {
      exit = 1;
    }
    if (exit === 1) {
      range = new Vscode.Range(new Vscode.Position(0, 0), new Vscode.Position(0, 1));
    }
    
  } else {
    range = new Vscode.Range(new Vscode.Position(0, 0), new Vscode.Position(0, 1));
  }
  var diagnostic = createDiagnostic(message, range, 1);
  var collection = getOrCreate();
  var existing = Core__Option.getOr(collection.get(uri), []);
  var newDiagnostics = existing.concat([diagnostic]);
  setDiagnostics(uri, newDiagnostics);
}

function dispose() {
  Core__Option.forEach(diagnosticsCollection.contents, (function (collection) {
          collection.dispose();
        }));
  diagnosticsCollection.contents = undefined;
}

exports.diagnosticsCollection = diagnosticsCollection;
exports.init = init;
exports.getOrCreate = getOrCreate;
exports.clear = clear;
exports.clearForUri = clearForUri;
exports.parseErrorRange = parseErrorRange;
exports.createDiagnostic = createDiagnostic;
exports.setDiagnostics = setDiagnostics;
exports.addError = addError;
exports.addWarning = addWarning;
exports.dispose = dispose;
/* vscode Not a pure module */
