// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__Option = require("@rescript/core/lib/js/src/Core__Option.bs.js");
var StatusBar$AgdaModeVscode = require("../StatusBar.bs.js");

var statusBar = {
  contents: undefined
};

function getOrCreate(context) {
  var sb = statusBar.contents;
  if (sb !== undefined) {
    return sb;
  }
  var sb$1 = StatusBar$AgdaModeVscode.create(context);
  StatusBar$AgdaModeVscode.registerVisibilityListeners(sb$1, context);
  statusBar.contents = sb$1;
  return sb$1;
}

function get() {
  return statusBar.contents;
}

function onLoadStart() {
  Core__Option.forEach(statusBar.contents, (function (sb) {
          StatusBar$AgdaModeVscode.update(sb, "Checking");
        }));
}

function onLoadSuccess() {
  Core__Option.forEach(statusBar.contents, (function (sb) {
          StatusBar$AgdaModeVscode.update(sb, "Success");
        }));
}

function onLoadError(errors) {
  Core__Option.forEach(statusBar.contents, (function (sb) {
          StatusBar$AgdaModeVscode.update(sb, {
                TAG: "Error",
                _0: errors
              });
        }));
}

function reset() {
  Core__Option.forEach(statusBar.contents, (function (sb) {
          StatusBar$AgdaModeVscode.update(sb, "Unchecked");
        }));
}

function setVersion(version) {
  Core__Option.forEach(statusBar.contents, (function (sb) {
          StatusBar$AgdaModeVscode.setVersion(sb, version);
        }));
}

function extractErrorMessages(info) {
  switch (info.TAG) {
    case "AllGoalsWarnings" :
        var body = info._1;
        if (body.includes("Error")) {
          return [body];
        } else {
          return ;
        }
    case "Error" :
        return [info._0];
    default:
      return ;
  }
}

function handleResponse(response) {
  if (typeof response !== "object") {
    return ;
  }
  switch (response.TAG) {
    case "InteractionPoints" :
        return onLoadSuccess();
    case "DisplayInfo" :
        var body = response._0;
        switch (body.TAG) {
          case "CompilationOk" :
              return onLoadSuccess();
          case "CompilationOkALS" :
              var errors = body._1;
              if (errors.length > 0) {
                return onLoadError(errors);
              } else {
                return onLoadSuccess();
              }
          case "AllGoalsWarnings" :
              var header = body._0;
              if (header.includes("Error")) {
                return onLoadError([header]);
              } else if (header.includes("All") && header.includes("checked")) {
                return onLoadSuccess();
              } else {
                return ;
              }
          case "AllGoalsWarningsALS" :
              var errors$1 = body._4;
              if (errors$1.length > 0) {
                return onLoadError(errors$1);
              } else if (body._3.length > 0 || body._0.includes("checked")) {
                return onLoadSuccess();
              } else {
                return ;
              }
          case "Error" :
              return onLoadError([body._0]);
          default:
            return ;
        }
    default:
      return ;
  }
}

function destroy() {
  Core__Option.forEach(statusBar.contents, (function (sb) {
          StatusBar$AgdaModeVscode.hide(sb);
        }));
  statusBar.contents = undefined;
}

exports.statusBar = statusBar;
exports.getOrCreate = getOrCreate;
exports.get = get;
exports.onLoadStart = onLoadStart;
exports.onLoadSuccess = onLoadSuccess;
exports.onLoadError = onLoadError;
exports.reset = reset;
exports.setVersion = setVersion;
exports.extractErrorMessages = extractErrorMessages;
exports.handleResponse = handleResponse;
exports.destroy = destroy;
/* StatusBar-AgdaModeVscode Not a pure module */
