// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Assert = require("assert");
var Common$AgdaModeVscode = require("../../src/View/Common.bs.js");

describe("Common.Tab", (function () {
        describe("toString", (function () {
                it("should convert Goals to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Tab.toString("Goals"), "Goals", undefined);
                      }));
                it("should convert Compile to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Tab.toString("Compile"), "Compile", undefined);
                      }));
                it("should convert AgdaFlags to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Tab.toString("AgdaFlags"), "Agda Flags", undefined);
                      }));
              }));
        describe("all", (function () {
                it("should contain Goals, Compile, and AgdaFlags", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Tab.all, [
                              "Goals",
                              "Compile",
                              "AgdaFlags"
                            ], undefined);
                      }));
                it("should have 3 tabs", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Tab.all.length, 3, undefined);
                      }));
              }));
        describe("fromString", (function () {
                it("should convert 'Goals' to Goals", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Tab.fromString("Goals"), "Goals", undefined);
                      }));
                it("should convert 'Compile' to Compile", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Tab.fromString("Compile"), "Compile", undefined);
                      }));
                it("should convert 'AgdaFlags' to AgdaFlags", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Tab.fromString("AgdaFlags"), "AgdaFlags", undefined);
                      }));
                it("should default to Goals for unknown strings", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Tab.fromString("Unknown"), "Goals", undefined);
                      }));
              }));
      }));

/*  Not a pure module */
