// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Assert = require("assert");
var Common$AgdaModeVscode = require("../../src/View/Common.bs.js");

describe("Common.Backend", (function () {
        describe("toString", (function () {
                it("should convert GHC to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.toString("GHC"), "GHC", undefined);
                      }));
                it("should convert GHCNoMain to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.toString("GHCNoMain"), "GHCNoMain", undefined);
                      }));
                it("should convert LaTeX to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.toString("LaTeX"), "LaTeX", undefined);
                      }));
                it("should convert QuickLaTeX to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.toString("QuickLaTeX"), "QuickLaTeX", undefined);
                      }));
                it("should convert HTML to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.toString("HTML"), "HTML", undefined);
                      }));
                it("should convert JS to string", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.toString("JS"), "JS", undefined);
                      }));
              }));
        describe("description", (function () {
                it("should return user-friendly description for GHC", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.description("GHC"), "GHC (with main)", undefined);
                      }));
                it("should return user-friendly description for GHCNoMain", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.description("GHCNoMain"), "GHC (library)", undefined);
                      }));
                it("should return user-friendly description for JS", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.description("JS"), "JavaScript", undefined);
                      }));
              }));
        describe("fromString", (function () {
                it("should convert GHC string to backend", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Backend.fromString("GHC"), "GHC", undefined);
                      }));
                it("should convert GHCNoMain string to backend", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Backend.fromString("GHCNoMain"), "GHCNoMain", undefined);
                      }));
                it("should convert LaTeX string to backend", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Backend.fromString("LaTeX"), "LaTeX", undefined);
                      }));
                it("should convert QuickLaTeX string to backend", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Backend.fromString("QuickLaTeX"), "QuickLaTeX", undefined);
                      }));
                it("should convert HTML string to backend", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Backend.fromString("HTML"), "HTML", undefined);
                      }));
                it("should convert JS string to backend", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Backend.fromString("JS"), "JS", undefined);
                      }));
                it("should default to GHC for unknown strings", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Backend.fromString("Unknown"), "GHC", undefined);
                      }));
              }));
        describe("all", (function () {
                it("should contain all 6 backends", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.Backend.all.length, 6, undefined);
                      }));
                it("should include all backends in order", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.Backend.all, [
                              "GHC",
                              "GHCNoMain",
                              "LaTeX",
                              "QuickLaTeX",
                              "HTML",
                              "JS"
                            ], undefined);
                      }));
              }));
      }));

describe("Common.CompileOptions", (function () {
        describe("default", (function () {
                it("should have GHC as default backend", (function () {
                        Curry._3(Assert.deepStrictEqual, Common$AgdaModeVscode.CompileOptions.$$default.backend, "GHC", undefined);
                      }));
                it("should have empty ghcOptions", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.CompileOptions.$$default.ghcOptions, "", undefined);
                      }));
                it("should have default outputPath", (function () {
                        Curry._3(Assert.strictEqual, Common$AgdaModeVscode.CompileOptions.$$default.outputPath, "./build", undefined);
                      }));
              }));
      }));

/*  Not a pure module */
