// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Assert = require("assert");
var State__StatusBar$AgdaModeVscode = require("../../src/State/State__StatusBar.bs.js");

describe("State__StatusBar", (function () {
        describe("extractErrorMessages", (function () {
                it("should extract error from Error response", (function () {
                        var result = State__StatusBar$AgdaModeVscode.extractErrorMessages({
                              TAG: "Error",
                              _0: "Test error"
                            });
                        Curry._3(Assert.deepStrictEqual, result, ["Test error"], undefined);
                      }));
                it("should return None for non-error responses", (function () {
                        var result = State__StatusBar$AgdaModeVscode.extractErrorMessages({
                              TAG: "CompilationOk",
                              _0: "Success"
                            });
                        Curry._3(Assert.deepStrictEqual, result, undefined, undefined);
                      }));
              }));
        describe("status updates", (function () {
                it("get should return None initially", (function () {
                        State__StatusBar$AgdaModeVscode.destroy();
                        var result = State__StatusBar$AgdaModeVscode.get();
                        Curry._3(Assert.deepStrictEqual, result, undefined, undefined);
                      }));
              }));
        describe("handleResponse", (function () {
                it("should handle DisplayInfo Error without crashing", (function () {
                        State__StatusBar$AgdaModeVscode.destroy();
                        State__StatusBar$AgdaModeVscode.handleResponse({
                              TAG: "DisplayInfo",
                              _0: {
                                TAG: "Error",
                                _0: "test error"
                              }
                            });
                        Assert.ok(true);
                      }));
                it("should handle InteractionPoints without crashing", (function () {
                        State__StatusBar$AgdaModeVscode.destroy();
                        State__StatusBar$AgdaModeVscode.handleResponse({
                              TAG: "InteractionPoints",
                              _0: [
                                1,
                                2,
                                3
                              ]
                            });
                        Assert.ok(true);
                      }));
                it("should handle DisplayInfo CompilationOk without crashing", (function () {
                        State__StatusBar$AgdaModeVscode.destroy();
                        State__StatusBar$AgdaModeVscode.handleResponse({
                              TAG: "DisplayInfo",
                              _0: {
                                TAG: "CompilationOk",
                                _0: "success"
                              }
                            });
                        Assert.ok(true);
                      }));
              }));
      }));

/*  Not a pure module */
