// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Assert = require("assert");
var StatusBar$AgdaModeVscode = require("../../src/StatusBar.bs.js");

describe("StatusBar", (function () {
        describe("statusToString", (function () {
                it("should convert Unchecked to string", (function () {
                        Curry._3(Assert.strictEqual, StatusBar$AgdaModeVscode.statusToString("Unchecked"), "Unchecked", undefined);
                      }));
                it("should convert Checking to string", (function () {
                        Curry._3(Assert.strictEqual, StatusBar$AgdaModeVscode.statusToString("Checking"), "Checking", undefined);
                      }));
                it("should convert Success to string", (function () {
                        Curry._3(Assert.strictEqual, StatusBar$AgdaModeVscode.statusToString("Success"), "Success", undefined);
                      }));
                it("should convert Error with 0 issues to string", (function () {
                        Curry._3(Assert.strictEqual, StatusBar$AgdaModeVscode.statusToString({
                                  TAG: "Error",
                                  _0: []
                                }), "Error(0 issues)", undefined);
                      }));
                it("should convert Error with 1 issue to string", (function () {
                        Curry._3(Assert.strictEqual, StatusBar$AgdaModeVscode.statusToString({
                                  TAG: "Error",
                                  _0: ["error1"]
                                }), "Error(1 issues)", undefined);
                      }));
                it("should convert Error with multiple issues to string", (function () {
                        Curry._3(Assert.strictEqual, StatusBar$AgdaModeVscode.statusToString({
                                  TAG: "Error",
                                  _0: [
                                    "error1",
                                    "error2",
                                    "error3"
                                  ]
                                }), "Error(3 issues)", undefined);
                      }));
              }));
        describe("isAgdaFile", (function () {
                it("should be defined", (function () {
                        Assert.ok(true);
                      }));
              }));
      }));

/*  Not a pure module */
