// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vscode = require("vscode");
var Caml_option = require("rescript/lib/js/caml_option.js");

function statusToString(status) {
  if (typeof status === "object") {
    return "Error(" + status._0.length.toString() + " issues)";
  }
  switch (status) {
    case "Unchecked" :
        return "Unchecked";
    case "Checking" :
        return "Checking";
    case "Success" :
        return "Success";
    
  }
}

function create(context) {
  var item = Vscode.window.createStatusBarItem(2, 100);
  item.command = "agda-mode.show-goals[AsIs]";
  item.tooltip = "Click to show Agda goals and errors";
  context.subscriptions.push(new Vscode.Disposable((function () {
              item.dispose();
            })));
  return {
          item: item,
          status: "Unchecked",
          errors: [],
          agdaVersion: undefined
        };
}

function formatLabel(icon, version) {
  if (version !== undefined) {
    return icon + " Agda " + version;
  } else {
    return icon + " Agda";
  }
}

function update(self, status) {
  self.status = status;
  if (typeof status !== "object") {
    switch (status) {
      case "Unchecked" :
          self.item.text = formatLabel("$(circle-outline)", self.agdaVersion);
          self.item.backgroundColor = null;
          self.item.tooltip = "Agda: Not loaded";
          self.errors = [];
          return ;
      case "Checking" :
          self.item.text = formatLabel("$(sync~spin)", self.agdaVersion);
          self.item.backgroundColor = null;
          self.item.tooltip = "Agda: Type checking...";
          self.errors = [];
          return ;
      case "Success" :
          self.item.text = formatLabel("$(check)", self.agdaVersion);
          self.item.backgroundColor = new Vscode.ThemeColor("statusBarItem.successBackground");
          self.item.tooltip = "Agda: Type check passed";
          self.errors = [];
          return ;
      
    }
  } else {
    var messages = status._0;
    self.item.text = formatLabel("$(error)", self.agdaVersion);
    self.item.backgroundColor = new Vscode.ThemeColor("statusBarItem.errorBackground");
    var errorCount = messages.length;
    var tooltip = "Agda: " + errorCount.toString() + (
      errorCount === 1 ? " error" : " errors"
    ) + " - Click to show";
    self.item.tooltip = tooltip;
    self.errors = messages;
    return ;
  }
}

function setVersion(self, version) {
  self.agdaVersion = version;
  update(self, self.status);
}

function show(self) {
  self.item.show();
}

function hide(self) {
  self.item.hide();
}

function getStatus(self) {
  return self.status;
}

function getErrors(self) {
  return self.errors;
}

function isAgdaFile($$document) {
  var languageId = $$document.languageId;
  if (languageId === "agda" || languageId === "lagda-markdown" || languageId === "lagda-tex" || languageId === "lagda-rst" || languageId === "lagda-org" || languageId === "lagda-typst") {
    return true;
  } else {
    return languageId === "lagda-forester";
  }
}

function updateVisibility(self, editor) {
  if (editor !== undefined) {
    var $$document = Caml_option.valFromOption(editor).document;
    if (isAgdaFile($$document)) {
      self.item.show();
    } else {
      self.item.hide();
    }
    return ;
  }
  self.item.hide();
}

function registerVisibilityListeners(self, context) {
  var disposable = Vscode.window.onDidChangeActiveTextEditor(function (editor) {
        updateVisibility(self, editor);
      });
  context.subscriptions.push(disposable);
  updateVisibility(self, Vscode.window.activeTextEditor);
}

var priority = 100;

exports.statusToString = statusToString;
exports.priority = priority;
exports.create = create;
exports.formatLabel = formatLabel;
exports.update = update;
exports.setVersion = setVersion;
exports.show = show;
exports.hide = hide;
exports.getStatus = getStatus;
exports.getErrors = getErrors;
exports.isAgdaFile = isAgdaFile;
exports.updateVisibility = updateVisibility;
exports.registerVisibilityListeners = registerVisibilityListeners;
/* vscode Not a pure module */
