// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function toString(norm) {
  switch (norm) {
    case "AsIs" :
        return "As Is";
    case "Simplified" :
        return "Simplified";
    case "Instantiated" :
        return "Instantiated";
    case "Normalised" :
        return "Normalised";
    case "HeadNormal" :
        return "Head Normal";
    
  }
}

function fromString(s) {
  switch (s) {
    case "HeadNormal" :
        return "HeadNormal";
    case "Instantiated" :
        return "Instantiated";
    case "Normalised" :
        return "Normalised";
    case "Simplified" :
        return "Simplified";
    default:
      return "AsIs";
  }
}

var all = [
  "Simplified",
  "Instantiated",
  "Normalised",
  "HeadNormal"
];

function CommandToolbar$NormalizationSelect(props) {
  var onChange = props.onChange;
  var handleChange = function ($$event) {
    var target = $$event.target;
    var value = target.value;
    onChange(fromString(value));
  };
  return React.createElement("select", {
              className: "normalization-select",
              id: props.id,
              value: toString(props.value),
              onChange: handleChange
            }, all.map(function (norm) {
                  var value = toString(norm);
                  return React.createElement("option", {
                              key: value,
                              value: value
                            }, value);
                }));
}

var NormalizationSelect = {
  toString: toString,
  fromString: fromString,
  all: all,
  make: CommandToolbar$NormalizationSelect
};

function toString$1(mode) {
  switch (mode) {
    case "DefaultCompute" :
        return "Default";
    case "IgnoreAbstract" :
        return "Ignore Abstract";
    case "UseShowInstance" :
        return "Use Show Instance";
    
  }
}

function fromString$1(s) {
  switch (s) {
    case "Ignore Abstract" :
        return "IgnoreAbstract";
    case "Use Show Instance" :
        return "UseShowInstance";
    default:
      return "DefaultCompute";
  }
}

var all$1 = [
  "DefaultCompute",
  "IgnoreAbstract",
  "UseShowInstance"
];

function CommandToolbar$ComputeModeSelect(props) {
  var onChange = props.onChange;
  var handleChange = function ($$event) {
    var target = $$event.target;
    var value = target.value;
    onChange(fromString$1(value));
  };
  return React.createElement("select", {
              className: "compute-mode-select",
              id: props.id,
              value: toString$1(props.value),
              onChange: handleChange
            }, all$1.map(function (mode) {
                  var value = toString$1(mode);
                  return React.createElement("option", {
                              key: value,
                              value: value
                            }, value);
                }));
}

var ComputeModeSelect = {
  toString: toString$1,
  fromString: fromString$1,
  all: all$1,
  make: CommandToolbar$ComputeModeSelect
};

function CommandToolbar$CommandButton(props) {
  var onClick = props.onClick;
  return React.createElement("button", {
              className: "command-button",
              title: props.title,
              onClick: (function (param) {
                  onClick();
                })
            }, React.createElement("span", {
                  className: "codicon " + props.icon
                }), " " + props.label);
}

var CommandButton = {
  make: CommandToolbar$CommandButton
};

function CommandToolbar$CommandWithDropdown(props) {
  var onExecute = props.onExecute;
  var normalization = props.normalization;
  return React.createElement("div", {
              className: "command-with-dropdown"
            }, React.createElement("button", {
                  className: "command-button with-dropdown",
                  title: props.title,
                  onClick: (function (param) {
                      onExecute(normalization);
                    })
                }, React.createElement("span", {
                      className: "codicon " + props.icon
                    }), " " + props.label), React.createElement(CommandToolbar$NormalizationSelect, {
                  value: normalization,
                  onChange: props.onNormalizationChange,
                  id: props.dropdownId
                }));
}

var CommandWithDropdown = {
  make: CommandToolbar$CommandWithDropdown
};

function CommandToolbar$ComputeNormalFormCommand(props) {
  var onExecute = props.onExecute;
  var computeMode = props.computeMode;
  return React.createElement("div", {
              className: "command-with-dropdown"
            }, React.createElement("button", {
                  className: "command-button with-dropdown",
                  title: "Compute normal form",
                  onClick: (function (param) {
                      onExecute(computeMode);
                    })
                }, React.createElement("span", {
                      className: "codicon codicon-symbol-numeric"
                    }), " Compute Normal Form"), React.createElement(CommandToolbar$ComputeModeSelect, {
                  value: computeMode,
                  onChange: props.onComputeModeChange,
                  id: "compute-mode-select"
                }));
}

var ComputeNormalFormCommand = {
  make: CommandToolbar$ComputeNormalFormCommand
};

function CommandToolbar(props) {
  var onCommand = props.onCommand;
  var match = React.useState(function () {
        return "Simplified";
      });
  var setGoalTypeNorm = match[1];
  var match$1 = React.useState(function () {
        return "Simplified";
      });
  var setGoalTypeContextNorm = match$1[1];
  var match$2 = React.useState(function () {
        return "Simplified";
      });
  var setContextNorm = match$2[1];
  var match$3 = React.useState(function () {
        return "Simplified";
      });
  var setInferTypeNorm = match$3[1];
  var match$4 = React.useState(function () {
        return "Simplified";
      });
  var setAutoNorm = match$4[1];
  var match$5 = React.useState(function () {
        return "Simplified";
      });
  var setElaborateGiveNorm = match$5[1];
  var match$6 = React.useState(function () {
        return "Simplified";
      });
  var setModuleContentsNorm = match$6[1];
  var match$7 = React.useState(function () {
        return "Simplified";
      });
  var setShowGoalsNorm = match$7[1];
  var match$8 = React.useState(function () {
        return "Simplified";
      });
  var setSolveConstraintsNorm = match$8[1];
  var match$9 = React.useState(function () {
        return "DefaultCompute";
      });
  var setComputeMode = match$9[1];
  var normToString = function (norm) {
    switch (norm) {
      case "AsIs" :
          return "AsIs";
      case "Simplified" :
          return "Simplified";
      case "Instantiated" :
          return "Instantiated";
      case "Normalised" :
          return "Normalised";
      case "HeadNormal" :
          return "HeadNormal";
      
    }
  };
  var computeModeToString = function (mode) {
    switch (mode) {
      case "DefaultCompute" :
          return "DefaultCompute";
      case "IgnoreAbstract" :
          return "IgnoreAbstract";
      case "UseShowInstance" :
          return "UseShowInstance";
      
    }
  };
  return React.createElement("div", {
              className: "command-toolbar"
            }, React.createElement("div", {
                  className: "toolbar-section"
                }, React.createElement("h4", undefined, "Query Goal"), React.createElement("div", {
                      className: "command-group"
                    }, React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Goal Type",
                          icon: "codicon-symbol-method",
                          normalization: match[0],
                          onNormalizationChange: (function (norm) {
                              setGoalTypeNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("goal-type[" + normToString(norm) + "]");
                            }),
                          dropdownId: "goal-type-norm",
                          title: "Show the type of the goal (Ctrl+C Ctrl+T)"
                        }), React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Goal Type & Context",
                          icon: "codicon-list-tree",
                          normalization: match$1[0],
                          onNormalizationChange: (function (norm) {
                              setGoalTypeContextNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("goal-type-and-context[" + normToString(norm) + "]");
                            }),
                          dropdownId: "goal-type-context-norm",
                          title: "Show goal type and context (Ctrl+C Ctrl+E)"
                        }), React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Context",
                          icon: "codicon-list-flat",
                          normalization: match$2[0],
                          onNormalizationChange: (function (norm) {
                              setContextNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("context[" + normToString(norm) + "]");
                            }),
                          dropdownId: "context-norm",
                          title: "Show context (Ctrl+C Ctrl+Shift+E)"
                        }))), React.createElement("div", {
                  className: "toolbar-section"
                }, React.createElement("h4", undefined, "Goal Operations"), React.createElement("div", {
                      className: "command-group"
                    }, React.createElement(CommandToolbar$CommandButton, {
                          label: "Give",
                          icon: "codicon-check",
                          onClick: (function () {
                              onCommand("give");
                            }),
                          title: "Fill goal with the given expression (Ctrl+C Ctrl+Space)"
                        }), React.createElement(CommandToolbar$CommandButton, {
                          label: "Refine",
                          icon: "codicon-lightbulb",
                          onClick: (function () {
                              onCommand("refine");
                            }),
                          title: "Refine goal (Ctrl+C Ctrl+R)"
                        }), React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Auto",
                          icon: "codicon-wand",
                          normalization: match$4[0],
                          onNormalizationChange: (function (norm) {
                              setAutoNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("auto[" + normToString(norm) + "]");
                            }),
                          dropdownId: "auto-norm",
                          title: "Search for proof automatically (Ctrl+C Ctrl+A)"
                        }), React.createElement(CommandToolbar$CommandButton, {
                          label: "Case Split",
                          icon: "codicon-split-horizontal",
                          onClick: (function () {
                              onCommand("case");
                            }),
                          title: "Case split on variable (Ctrl+C Ctrl+C)"
                        }), React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Elaborate & Give",
                          icon: "codicon-bracket-dot",
                          normalization: match$5[0],
                          onNormalizationChange: (function (norm) {
                              setElaborateGiveNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("elaborate-and-give[" + normToString(norm) + "]");
                            }),
                          dropdownId: "elaborate-give-norm",
                          title: "Elaborate and give (Ctrl+C Ctrl+M)"
                        }))), React.createElement("div", {
                  className: "toolbar-section"
                }, React.createElement("h4", undefined, "Inspect Expression"), React.createElement("div", {
                      className: "command-group"
                    }, React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Infer Type",
                          icon: "codicon-symbol-interface",
                          normalization: match$3[0],
                          onNormalizationChange: (function (norm) {
                              setInferTypeNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("infer-type[" + normToString(norm) + "]");
                            }),
                          dropdownId: "infer-type-norm",
                          title: "Infer type of expression (Ctrl+C Ctrl+D)"
                        }), React.createElement(CommandToolbar$ComputeNormalFormCommand, {
                          computeMode: match$9[0],
                          onComputeModeChange: (function (mode) {
                              setComputeMode(function (param) {
                                    return mode;
                                  });
                            }),
                          onExecute: (function (mode) {
                              onCommand("compute-normal-form[" + computeModeToString(mode) + "]");
                            })
                        }), React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Module Contents",
                          icon: "codicon-symbol-namespace",
                          normalization: match$6[0],
                          onNormalizationChange: (function (norm) {
                              setModuleContentsNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("module-contents[" + normToString(norm) + "]");
                            }),
                          dropdownId: "module-contents-norm",
                          title: "Show module contents (Ctrl+C Ctrl+O)"
                        }), React.createElement(CommandToolbar$CommandButton, {
                          label: "Why In Scope",
                          icon: "codicon-search",
                          onClick: (function () {
                              onCommand("why-in-scope");
                            }),
                          title: "Why is identifier in scope (Ctrl+C Ctrl+W)"
                        }))), React.createElement("div", {
                  className: "toolbar-section"
                }, React.createElement("h4", undefined, "Global Commands"), React.createElement("div", {
                      className: "command-group"
                    }, React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Show Goals",
                          icon: "codicon-checklist",
                          normalization: match$7[0],
                          onNormalizationChange: (function (norm) {
                              setShowGoalsNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("show-goals[" + normToString(norm) + "]");
                            }),
                          dropdownId: "show-goals-norm",
                          title: "Show all goals"
                        }), React.createElement(CommandToolbar$CommandButton, {
                          label: "Show Constraints",
                          icon: "codicon-warning",
                          onClick: (function () {
                              onCommand("show-constraints");
                            }),
                          title: "Show constraints (Ctrl+C Ctrl+=)"
                        }), React.createElement(CommandToolbar$CommandWithDropdown, {
                          label: "Solve Constraints",
                          icon: "codicon-debug-stackframe-dot",
                          normalization: match$8[0],
                          onNormalizationChange: (function (norm) {
                              setSolveConstraintsNorm(function (param) {
                                    return norm;
                                  });
                            }),
                          onExecute: (function (norm) {
                              onCommand("solve-constraints[" + normToString(norm) + "]");
                            }),
                          dropdownId: "solve-constraints-norm",
                          title: "Solve constraints"
                        }), React.createElement(CommandToolbar$CommandButton, {
                          label: "Next Goal",
                          icon: "codicon-arrow-down",
                          onClick: (function () {
                              onCommand("next-goal");
                            }),
                          title: "Jump to next goal (Ctrl+C Ctrl+F)"
                        }), React.createElement(CommandToolbar$CommandButton, {
                          label: "Previous Goal",
                          icon: "codicon-arrow-up",
                          onClick: (function () {
                              onCommand("previous-goal");
                            }),
                          title: "Jump to previous goal (Ctrl+C Ctrl+B)"
                        }))));
}

var make = CommandToolbar;

exports.NormalizationSelect = NormalizationSelect;
exports.ComputeModeSelect = ComputeModeSelect;
exports.CommandButton = CommandButton;
exports.CommandWithDropdown = CommandWithDropdown;
exports.ComputeNormalFormCommand = ComputeNormalFormCommand;
exports.make = make;
/* react Not a pure module */
