// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var JsxPPXReactSupportU = require("rescript/lib/js/jsxPPXReactSupportU.js");
var Common$AgdaModeVscode = require("../Common.bs.js");

function CompileTab$BackendSelect(props) {
  var onChange = props.onChange;
  var handleChange = function ($$event) {
    var target = $$event.target;
    var value = target.value;
    onChange(Common$AgdaModeVscode.Backend.fromString(value));
  };
  return React.createElement("div", {
              className: "option-row"
            }, React.createElement("label", {
                  htmlFor: "backend-select"
                }, "Backend:"), React.createElement("select", {
                  id: "backend-select",
                  value: Common$AgdaModeVscode.Backend.toString(props.value),
                  onChange: handleChange
                }, Common$AgdaModeVscode.Backend.all.map(function (b) {
                      var value = Common$AgdaModeVscode.Backend.toString(b);
                      var label = Common$AgdaModeVscode.Backend.description(b);
                      return React.createElement("option", {
                                  key: value,
                                  value: value
                                }, label);
                    })));
}

var BackendSelect = {
  make: CompileTab$BackendSelect
};

function CompileTab$TextInput(props) {
  var onChange = props.onChange;
  var id = props.id;
  var handleChange = function ($$event) {
    var target = $$event.target;
    onChange(target.value);
  };
  return React.createElement("div", {
              className: "option-row"
            }, React.createElement("label", {
                  htmlFor: id
                }, props.label), React.createElement("input", {
                  id: id,
                  placeholder: props.placeholder,
                  type: "text",
                  value: props.value,
                  onChange: handleChange
                }));
}

var TextInput = {
  make: CompileTab$TextInput
};

function CompileTab$Checkbox(props) {
  var onChange = props.onChange;
  var id = props.id;
  var handleChange = function ($$event) {
    var target = $$event.target;
    onChange(target.checked);
  };
  return React.createElement("div", {
              className: "option-row checkbox"
            }, React.createElement("input", {
                  id: id,
                  checked: props.checked,
                  type: "checkbox",
                  onChange: handleChange
                }), React.createElement("label", {
                  htmlFor: id
                }, props.label));
}

var Checkbox = {
  make: CompileTab$Checkbox
};

function CompileTab$CompileButton(props) {
  var isCompiling = props.isCompiling;
  var onClick = props.onClick;
  return React.createElement("button", {
              className: "compile-button" + (
                isCompiling ? " compiling" : ""
              ),
              disabled: isCompiling,
              onClick: (function (param) {
                  onClick();
                })
            }, isCompiling ? React.createElement(React.Fragment, {}, React.createElement("span", {
                        className: "codicon codicon-sync spin"
                      }), " Compiling...") : React.createElement(React.Fragment, {}, React.createElement("span", {
                        className: "codicon codicon-play"
                      }), " Compile"));
}

var CompileButton = {
  make: CompileTab$CompileButton
};

function CompileTab$OutputDisplay(props) {
  var output = props.output;
  var className = "compile-output" + (
    props.isError ? " error" : ""
  );
  return React.createElement("div", {
              className: className
            }, output.length > 0 ? React.createElement("pre", undefined, output.map(function (line, i) {
                        return JsxPPXReactSupportU.createElementVariadicWithKey(i.toString(), React.Fragment, {
                                    children: null
                                  }, [
                                    line,
                                    "\n"
                                  ]);
                      })) : React.createElement("div", {
                    className: "compile-output-empty"
                  }, props.emptyMessage));
}

var OutputDisplay = {
  make: CompileTab$OutputDisplay
};

function CompileTab$CommandPreview(props) {
  var command = props.command;
  if (command === "") {
    return null;
  } else {
    return React.createElement("div", {
                className: "command-preview-section"
              }, React.createElement("label", undefined, "Command Preview:"), React.createElement("code", {
                    className: "command-preview"
                  }, command));
  }
}

var CommandPreview = {
  make: CompileTab$CommandPreview
};

function CompileTab$RunCommandInput(props) {
  var disabled = props.disabled;
  var onRun = props.onRun;
  var onChange = props.onChange;
  var handleChange = function ($$event) {
    var target = $$event.target;
    onChange(target.value);
  };
  return React.createElement("div", {
              className: "option-row run-command-row"
            }, React.createElement("label", {
                  htmlFor: "run-command"
                }, "Run Command:"), React.createElement("div", {
                  className: "run-command-input-group"
                }, React.createElement("input", {
                      className: "run-command-input",
                      id: "run-command",
                      placeholder: "./Main",
                      type: "text",
                      value: props.value,
                      onChange: handleChange
                    }), React.createElement("button", {
                      className: "run-button" + (
                        disabled ? " disabled" : ""
                      ),
                      title: "Run the compiled binary in a terminal",
                      disabled: disabled,
                      onClick: (function (param) {
                          onRun();
                        })
                    }, React.createElement("span", {
                          className: "codicon codicon-terminal"
                        }), " Run")));
}

var RunCommandInput = {
  make: CompileTab$RunCommandInput
};

function CompileTab$GhcOptionsSection(props) {
  var onChange = props.onChange;
  var options = props.options;
  return React.createElement("div", {
              className: "backend-options"
            }, React.createElement(CompileTab$TextInput, {
                  id: "main-module",
                  label: "Main Module:",
                  value: options.mainModule,
                  placeholder: "(current file)",
                  onChange: (function (mainModule) {
                      onChange({
                            backend: options.backend,
                            ghcOptions: options.ghcOptions,
                            mainModule: mainModule,
                            runCommand: options.runCommand,
                            outputPath: options.outputPath,
                            htmlOptions: options.htmlOptions,
                            latexOptions: options.latexOptions
                          });
                    })
                }), React.createElement(CompileTab$TextInput, {
                  id: "ghc-options",
                  label: "GHC Flags:",
                  value: options.ghcOptions,
                  placeholder: "-O2 -Wall",
                  onChange: (function (ghcOptions) {
                      onChange({
                            backend: options.backend,
                            ghcOptions: ghcOptions,
                            mainModule: options.mainModule,
                            runCommand: options.runCommand,
                            outputPath: options.outputPath,
                            htmlOptions: options.htmlOptions,
                            latexOptions: options.latexOptions
                          });
                    })
                }), React.createElement(CompileTab$RunCommandInput, {
                  value: options.runCommand,
                  onChange: (function (runCommand) {
                      onChange({
                            backend: options.backend,
                            ghcOptions: options.ghcOptions,
                            mainModule: options.mainModule,
                            runCommand: runCommand,
                            outputPath: options.outputPath,
                            htmlOptions: options.htmlOptions,
                            latexOptions: options.latexOptions
                          });
                    }),
                  onRun: props.onRun,
                  disabled: props.isCompiling
                }));
}

var GhcOptionsSection = {
  make: CompileTab$GhcOptionsSection
};

function CompileTab$HtmlOptionsSection(props) {
  var onChange = props.onChange;
  var options = props.options;
  var htmlOpts = options.htmlOptions;
  return React.createElement("div", {
              className: "backend-options"
            }, React.createElement(CompileTab$TextInput, {
                  id: "html-css-dir",
                  label: "CSS Directory:",
                  value: htmlOpts.cssDir,
                  placeholder: "./css",
                  onChange: (function (cssDir) {
                      onChange({
                            backend: options.backend,
                            ghcOptions: options.ghcOptions,
                            mainModule: options.mainModule,
                            runCommand: options.runCommand,
                            outputPath: options.outputPath,
                            htmlOptions: {
                              cssDir: cssDir,
                              highlightOccurrences: htmlOpts.highlightOccurrences,
                              onlyCode: htmlOpts.onlyCode
                            },
                            latexOptions: options.latexOptions
                          });
                    })
                }), React.createElement(CompileTab$Checkbox, {
                  id: "html-only-code",
                  label: "Only code (no navigation)",
                  checked: htmlOpts.onlyCode,
                  onChange: (function (onlyCode) {
                      onChange({
                            backend: options.backend,
                            ghcOptions: options.ghcOptions,
                            mainModule: options.mainModule,
                            runCommand: options.runCommand,
                            outputPath: options.outputPath,
                            htmlOptions: {
                              cssDir: htmlOpts.cssDir,
                              highlightOccurrences: htmlOpts.highlightOccurrences,
                              onlyCode: onlyCode
                            },
                            latexOptions: options.latexOptions
                          });
                    })
                }), React.createElement(CompileTab$Checkbox, {
                  id: "html-highlight",
                  label: "Highlight occurrences",
                  checked: htmlOpts.highlightOccurrences,
                  onChange: (function (highlightOccurrences) {
                      onChange({
                            backend: options.backend,
                            ghcOptions: options.ghcOptions,
                            mainModule: options.mainModule,
                            runCommand: options.runCommand,
                            outputPath: options.outputPath,
                            htmlOptions: {
                              cssDir: htmlOpts.cssDir,
                              highlightOccurrences: highlightOccurrences,
                              onlyCode: htmlOpts.onlyCode
                            },
                            latexOptions: options.latexOptions
                          });
                    })
                }));
}

var HtmlOptionsSection = {
  make: CompileTab$HtmlOptionsSection
};

function CompileTab$LatexOptionsSection(props) {
  var onChange = props.onChange;
  var options = props.options;
  return React.createElement("div", {
              className: "backend-options"
            }, React.createElement(CompileTab$Checkbox, {
                  id: "latex-count-clusters",
                  label: "Count clusters",
                  checked: options.latexOptions.countClusters,
                  onChange: (function (countClusters) {
                      onChange({
                            backend: options.backend,
                            ghcOptions: options.ghcOptions,
                            mainModule: options.mainModule,
                            runCommand: options.runCommand,
                            outputPath: options.outputPath,
                            htmlOptions: options.htmlOptions,
                            latexOptions: {
                              countClusters: countClusters
                            }
                          });
                    })
                }));
}

var LatexOptionsSection = {
  make: CompileTab$LatexOptionsSection
};

function CompileTab(props) {
  var onRun = props.onRun;
  var isCompiling = props.isCompiling;
  var onOptionsChange = props.onOptionsChange;
  var options = props.options;
  var match = options.backend;
  var backendOptions;
  var exit = 0;
  switch (match) {
    case "GHC" :
    case "GHCNoMain" :
        exit = 1;
        break;
    case "LaTeX" :
    case "QuickLaTeX" :
        backendOptions = React.createElement(CompileTab$LatexOptionsSection, {
              options: options,
              onChange: onOptionsChange
            });
        break;
    case "HTML" :
        backendOptions = React.createElement(CompileTab$HtmlOptionsSection, {
              options: options,
              onChange: onOptionsChange
            });
        break;
    case "JS" :
        backendOptions = null;
        break;
    
  }
  if (exit === 1) {
    backendOptions = React.createElement(CompileTab$GhcOptionsSection, {
          options: options,
          onChange: onOptionsChange,
          onRun: (function () {
              onRun(options.runCommand, options.outputPath);
            }),
          isCompiling: isCompiling
        });
  }
  return React.createElement("div", {
              className: "agda-mode-compile-tab"
            }, React.createElement("div", {
                  className: "options-section"
                }, React.createElement("h3", undefined, "Compile Options"), React.createElement(CompileTab$CommandPreview, {
                      command: props.commandPreview
                    }), React.createElement(CompileTab$BackendSelect, {
                      value: options.backend,
                      onChange: (function (backend) {
                          onOptionsChange({
                                backend: backend,
                                ghcOptions: options.ghcOptions,
                                mainModule: options.mainModule,
                                runCommand: options.runCommand,
                                outputPath: options.outputPath,
                                htmlOptions: options.htmlOptions,
                                latexOptions: options.latexOptions
                              });
                        })
                    }), React.createElement(CompileTab$TextInput, {
                      id: "output-path",
                      label: "Output Path:",
                      value: options.outputPath,
                      placeholder: "./build",
                      onChange: (function (outputPath) {
                          onOptionsChange({
                                backend: options.backend,
                                ghcOptions: options.ghcOptions,
                                mainModule: options.mainModule,
                                runCommand: options.runCommand,
                                outputPath: outputPath,
                                htmlOptions: options.htmlOptions,
                                latexOptions: options.latexOptions
                              });
                        })
                    }), backendOptions, React.createElement("div", {
                      className: "button-row"
                    }, React.createElement(CompileTab$CompileButton, {
                          onClick: props.onCompile,
                          isCompiling: isCompiling
                        }))), React.createElement("div", {
                  className: "output-section"
                }, React.createElement("h3", undefined, "Output"), React.createElement(CompileTab$OutputDisplay, {
                      output: props.output,
                      isError: props.isError,
                      emptyMessage: "No compilation output yet. Click Compile to build."
                    })));
}

var make = CompileTab;

exports.BackendSelect = BackendSelect;
exports.TextInput = TextInput;
exports.Checkbox = Checkbox;
exports.CompileButton = CompileButton;
exports.OutputDisplay = OutputDisplay;
exports.CommandPreview = CommandPreview;
exports.RunCommandInput = RunCommandInput;
exports.GhcOptionsSection = GhcOptionsSection;
exports.HtmlOptionsSection = HtmlOptionsSection;
exports.LatexOptionsSection = LatexOptionsSection;
exports.make = make;
/* react Not a pure module */
