// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Body$AgdaModeVscode = require("./Body.bs.js");
var View$AgdaModeVscode = require("../View.bs.js");

function GoalsTab(props) {
  var connectionStatus = props.connectionStatus;
  var header = props.header;
  var headerClassName;
  switch (header.TAG) {
    case "Plain" :
        headerClassName = "agda-mode-goals-header";
        break;
    case "Success" :
        headerClassName = "agda-mode-goals-header success";
        break;
    case "Warning" :
        headerClassName = "agda-mode-goals-header warning";
        break;
    case "Error" :
        headerClassName = "agda-mode-goals-header error";
        break;
    
  }
  var headerText = View$AgdaModeVscode.Header.toString(header);
  return React.createElement("div", {
              className: "agda-mode-goals-tab"
            }, React.createElement("div", {
                  className: headerClassName
                }, React.createElement("span", {
                      className: "header-text"
                    }, headerText), connectionStatus !== "" ? React.createElement("span", {
                        className: "connection-status"
                      }, connectionStatus) : null), React.createElement("div", {
                  className: "agda-mode-goals-body"
                }, React.createElement(Body$AgdaModeVscode.make, {
                      items: props.items
                    })));
}

var make = GoalsTab;

exports.make = make;
/* react Not a pure module */
