// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Common$AgdaModeVscode = require("../Common.bs.js");

function OptionsTab$FlagCheckbox(props) {
  var onChange = props.onChange;
  var id = props.id;
  return React.createElement("div", {
              className: "flag-row"
            }, React.createElement("label", {
                  className: "flag-checkbox-label",
                  htmlFor: id
                }, React.createElement("input", {
                      id: id,
                      checked: props.checked,
                      type: "checkbox",
                      onChange: (function (e) {
                          onChange(e.target.checked);
                        })
                    }), React.createElement("span", {
                      className: "flag-name"
                    }, props.flag)), React.createElement("span", {
                  className: "flag-description"
                }, props.description));
}

var FlagCheckbox = {
  make: OptionsTab$FlagCheckbox
};

function OptionsTab$OptionInput(props) {
  var onChange = props.onChange;
  var id = props.id;
  return React.createElement("div", {
              className: "option-input-row"
            }, React.createElement("label", {
                  className: "option-label",
                  htmlFor: id
                }, props.label), React.createElement("input", {
                  className: "option-text-input",
                  id: id,
                  placeholder: props.placeholder,
                  type: "text",
                  value: props.value,
                  onChange: (function (e) {
                      onChange(e.target.value);
                    })
                }));
}

var OptionInput = {
  make: OptionsTab$OptionInput
};

function OptionsTab(props) {
  var onFlagsChange = props.onFlagsChange;
  var flags = props.flags;
  var args = Common$AgdaModeVscode.AgdaFlags.toArgs(flags);
  var flagsStr = args.length > 0 ? " " + args.join(" ") : "";
  return React.createElement("div", {
              className: "agda-mode-options-tab"
            }, React.createElement("div", {
                  className: "options-section"
                }, React.createElement("h3", undefined, "Type Theory"), React.createElement("div", {
                      className: "flags-group"
                    }, React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-safe",
                          flag: "--safe",
                          description: "Disable postulates, primTrustMe, etc.",
                          checked: flags.safe,
                          onChange: (function (safe) {
                              onFlagsChange({
                                    safe: safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-without-k",
                          flag: "--without-K",
                          description: "Disable K rule (HoTT compatible)",
                          checked: flags.withoutK,
                          onChange: (function (withoutK) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-cubical-compatible",
                          flag: "--cubical-compatible",
                          description: "Implies --without-K",
                          checked: flags.cubicalCompatible,
                          onChange: (function (cubicalCompatible) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-prop",
                          flag: "--prop",
                          description: "Enable Prop universe",
                          checked: flags.prop,
                          onChange: (function (prop) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-two-level",
                          flag: "--two-level",
                          description: "Enable SSet* (strict sets)",
                          checked: flags.twoLevel,
                          onChange: (function (twoLevel) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-cumulativity",
                          flag: "--cumulativity",
                          description: "Set ≤ Set₁",
                          checked: flags.cumulativity,
                          onChange: (function (cumulativity) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }))), React.createElement("div", {
                  className: "options-section"
                }, React.createElement("h3", undefined, "Termination & Recursion"), React.createElement("div", {
                      className: "flags-group"
                    }, React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-guardedness",
                          flag: "--guardedness",
                          description: "Guarded corecursion",
                          checked: flags.guardedness,
                          onChange: (function (guardedness) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-sized-types",
                          flag: "--sized-types",
                          description: "Sized types",
                          checked: flags.sizedTypes,
                          onChange: (function (sizedTypes) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-no-termination-check",
                          flag: "--no-termination-check",
                          description: "⚠ Unsafe",
                          checked: flags.noTerminationCheck,
                          onChange: (function (noTerminationCheck) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-no-positivity-check",
                          flag: "--no-positivity-check",
                          description: "⚠ Unsafe",
                          checked: flags.noPositivityCheck,
                          onChange: (function (noPositivityCheck) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }))), React.createElement("div", {
                  className: "options-section"
                }, React.createElement("h3", undefined, "Display"), React.createElement("div", {
                      className: "flags-group"
                    }, React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-show-implicit",
                          flag: "--show-implicit",
                          description: "Show implicit args",
                          checked: flags.showImplicit,
                          onChange: (function (showImplicit) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-show-irrelevant",
                          flag: "--show-irrelevant",
                          description: "Show irrelevant args",
                          checked: flags.showIrrelevant,
                          onChange: (function (showIrrelevant) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }))), React.createElement("div", {
                  className: "options-section"
                }, React.createElement("h3", undefined, "Warnings & Errors"), React.createElement("div", {
                      className: "flags-group"
                    }, React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-werror",
                          flag: "-Werror",
                          description: "Warnings as errors",
                          checked: flags.warningError,
                          onChange: (function (warningError) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-allow-unsolved-metas",
                          flag: "--allow-unsolved-metas",
                          description: "Allow unsolved metas",
                          checked: flags.allowUnsolvedMetas,
                          onChange: (function (allowUnsolvedMetas) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-allow-incomplete-matches",
                          flag: "--allow-incomplete-matches",
                          description: "Allow incomplete matches",
                          checked: flags.allowIncompleteMatches,
                          onChange: (function (allowIncompleteMatches) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }))), React.createElement("div", {
                  className: "options-section"
                }, React.createElement("h3", undefined, "Debug & Verbose"), React.createElement("div", {
                      className: "flags-group"
                    }, React.createElement(OptionsTab$FlagCheckbox, {
                          id: "flag-only-scope-checking",
                          flag: "--only-scope-checking",
                          description: "Only scope check",
                          checked: flags.onlyScopeChecking,
                          onChange: (function (onlyScopeChecking) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        })), React.createElement("div", {
                      className: "options-group"
                    }, React.createElement(OptionsTab$OptionInput, {
                          id: "opt-verbose",
                          label: "Verbose (-v):",
                          placeholder: "e.g., 10 or scope:20",
                          value: flags.verboseLevel,
                          onChange: (function (verboseLevel) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: flags.includePath
                                  });
                            })
                        }))), React.createElement("div", {
                  className: "options-section"
                }, React.createElement("h3", undefined, "Paths"), React.createElement("div", {
                      className: "options-group"
                    }, React.createElement(OptionsTab$OptionInput, {
                          id: "opt-library",
                          label: "Library (-l):",
                          placeholder: "e.g., standard-library",
                          value: flags.library,
                          onChange: (function (library) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: library,
                                    includePath: flags.includePath
                                  });
                            })
                        }), React.createElement(OptionsTab$OptionInput, {
                          id: "opt-include-path",
                          label: "Include (-i):",
                          placeholder: "e.g., ./src",
                          value: flags.includePath,
                          onChange: (function (includePath) {
                              onFlagsChange({
                                    safe: flags.safe,
                                    withoutK: flags.withoutK,
                                    cubicalCompatible: flags.cubicalCompatible,
                                    prop: flags.prop,
                                    twoLevel: flags.twoLevel,
                                    cumulativity: flags.cumulativity,
                                    guardedness: flags.guardedness,
                                    sizedTypes: flags.sizedTypes,
                                    noTerminationCheck: flags.noTerminationCheck,
                                    noPositivityCheck: flags.noPositivityCheck,
                                    showImplicit: flags.showImplicit,
                                    showIrrelevant: flags.showIrrelevant,
                                    warningError: flags.warningError,
                                    allowUnsolvedMetas: flags.allowUnsolvedMetas,
                                    allowIncompleteMatches: flags.allowIncompleteMatches,
                                    verboseLevel: flags.verboseLevel,
                                    onlyScopeChecking: flags.onlyScopeChecking,
                                    library: flags.library,
                                    includePath: includePath
                                  });
                            })
                        }))), React.createElement("div", {
                  className: "options-section active-flags-section"
                }, React.createElement("h3", undefined, "Typecheck Command Preview"), React.createElement("div", {
                      className: "active-flags"
                    }, React.createElement("code", {
                          className: "flags-preview"
                        }, "agda --interaction" + flagsStr + " <file>")), React.createElement("div", {
                      className: "restart-note"
                    }, React.createElement("span", {
                          className: "codicon codicon-info"
                        }), " Changes require restarting the Agda connection (C-c C-x C-r)")));
}

var make = OptionsTab;

exports.FlagCheckbox = FlagCheckbox;
exports.OptionInput = OptionInput;
exports.make = make;
/* react Not a pure module */
