// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var JsxPPXReactSupportU = require("rescript/lib/js/jsxPPXReactSupportU.js");
var Common$AgdaModeVscode = require("../Common.bs.js");

function tabIconClass(tab) {
  switch (tab) {
    case "Goals" :
        return "codicon-checklist";
    case "Compile" :
        return "codicon-package";
    case "AgdaFlags" :
        return "codicon-settings-gear";
    
  }
}

function Tabs$TabButton(props) {
  var onClick = props.onClick;
  var tab = props.tab;
  var className = "tab" + (
    props.isActive ? " active" : ""
  );
  var iconClass = "codicon " + tabIconClass(tab);
  return React.createElement("div", {
              className: className,
              onClick: (function (param) {
                  onClick();
                })
            }, React.createElement("span", {
                  className: iconClass
                }), " " + Common$AgdaModeVscode.Tab.toString(tab));
}

var TabButton = {
  make: Tabs$TabButton
};

function Tabs(props) {
  var onTabChange = props.onTabChange;
  var activeTab = props.activeTab;
  return React.createElement("div", {
              className: "agda-mode-tabs"
            }, Common$AgdaModeVscode.Tab.all.map(function (tab) {
                  return JsxPPXReactSupportU.createElementWithKey(Common$AgdaModeVscode.Tab.toString(tab), Tabs$TabButton, {
                              tab: tab,
                              isActive: tab === activeTab,
                              onClick: (function () {
                                  onTabChange(tab);
                                })
                            });
                }));
}

var make = Tabs;

exports.tabIconClass = tabIconClass;
exports.TabButton = TabButton;
exports.make = make;
/* react Not a pure module */
